### ISSUE TITLE
org.autorefactor.jdt.internal.ui.fix.ArrayDequeRatherThanStackCleanUp is faulty

### ISSUE THREAD

**Issue by vogella** [JnRouvignac/AutoRefactor#404]
Running the ArrayDequeRatherThanStackCleanUp on the PDE code base results in lots of the following exceptions.

org.autorefactor.util.UnhandledException: RemotePluginTestRunner.java:1:1:Visitor org.autorefactor.jdt.internal.ui.fix.ArrayDequeRatherThanStackCleanUp is faulty, it will be disabled for the rest of this run.
	at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.logFaultyVisitor(AggregateASTVisitor.java:364)
	at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.visit(AggregateASTVisitor.java:1966)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:250)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2874)
	at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.getRefactorings(AggregateASTVisitor.java:304)
	at org.autorefactor.jdt.internal.corext.dom.ApplyRefactoringsJob.applyRefactoring(ApplyRefactoringsJob.java:253)
	at org.autorefactor.jdt.internal.corext.dom.ApplyRefactoringsJob.applyRefactoring(ApplyRefactoringsJob.java:180)
	at org.autorefactor.jdt.internal.corext.dom.ApplyRefactoringsJob.run0(ApplyRefactoringsJob.java:123)
	at org.autorefactor.jdt.internal.corext.dom.ApplyRefactoringsJob.run(ApplyRefactoringsJob.java:94)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
	at org.autorefactor.jdt.internal.ui.fix.NewClassImportCleanUp.filterLocallyUsedNames(NewClassImportCleanUp.java:241)
	at org.autorefactor.jdt.internal.ui.fix.NewClassImportCleanUp.visit(NewClassImportCleanUp.java:191)
	at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.visit(AggregateASTVisitor.java:1962)
	... 8 more

**Comment by vogella** [comment]
Still the case in the latest autorefactor develoment head

**Comment by Fabrice-TIERCELIN** [comment]
@vogella, tell us if it is still the case

**Comment by vogella** [comment]
Cannot reproduce anymore. I reverted the manual change I did and run the refactoring without exception

**Comment by vogella** [comment]
Just re-ran the cleanup as I discovered more usages of Stack in our code base and got:

org.autorefactor.util.UnhandledException: AbstractExtensionsModel.java:70:41:Visitor org.autorefactor.jdt.internal.ui.fix.RemoveUnnecessaryLocalBeforeReturnCleanUp is faulty, it will be disabled for the rest of this run.
	at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.logFaultyVisitor(AggregateASTVisitor.java:371)
	at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.visit(AggregateASTVisitor.java:1847)
	at org.eclipse.jdt.core.dom.Block.accept0(Block.java:126)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2975)
	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:617)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2998)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:447)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2998)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:258)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
	at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.getRefactorings(AggregateASTVisitor.java:310)
	at org.autorefactor.jdt.internal.corext.dom.ApplyRefactoringsJob.applyRefactoring(ApplyRefactoringsJob.java:250)
	at org.autorefactor.jdt.internal.corext.dom.ApplyRefactoringsJob.applyRefactoring(ApplyRefactoringsJob.java:176)
	at org.autorefactor.jdt.internal.corext.dom.ApplyRefactoringsJob.run0(ApplyRefactoringsJob.java:117)
	at org.autorefactor.jdt.internal.corext.dom.ApplyRefactoringsJob.run(ApplyRefactoringsJob.java:90)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassCastException: org.eclipse.jdt.core.dom.SimpleType incompatible with org.eclipse.jdt.core.dom.ArrayType
	at org.autorefactor.jdt.internal.ui.fix.RemoveUnnecessaryLocalBeforeReturnCleanUp$ReturnStatementVisitor.removeVariable(RemoveUnnecessaryLocalBeforeReturnCleanUp.java:142)
	at org.autorefactor.jdt.internal.ui.fix.RemoveUnnecessaryLocalBeforeReturnCleanUp$ReturnStatementVisitor.visit(RemoveUnnecessaryLocalBeforeReturnCleanUp.java:101)
	at org.eclipse.jdt.core.dom.ReturnStatement.accept0(ReturnStatement.java:126)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2998)
	at org.eclipse.jdt.core.dom.Block.accept0(Block.java:128)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
	at org.autorefactor.jdt.internal.ui.fix.RemoveUnnecessaryLocalBeforeReturnCleanUp.visit(RemoveUnnecessaryLocalBeforeReturnCleanUp.java:83)
	at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.visit(AggregateASTVisitor.java:1843)
	... 17 more

**Comment by cal101** [comment]
But your failing cleanup is RemoveUnnecessaryLocalBeforeReturnCleanUp this time ;-)

Can you provide the source code around (I guess) AbstractExtensionsModel.java:70:41?

btw. In your article about cleanup actions your link to "eclipse clean up guide" is dead. Do you have an updated link?

**Comment by vogella** [comment]
@cal101 I'm running the cleanups on the Eclipse code base. :-) AbstractExtensionsModel is located in the PDE git repo. See https://git.eclipse.org/r/#/admin/projects/pde/eclipse.pde.ui to see how to clone it.

> btw. In your article about cleanup actions your link to "eclipse clean up guide" is dead.

Which article?

**Comment by cal101** [comment]
Sorry. https://www.vogella.com/tutorials/EclipseJDT/article.html

**Comment by cal101** [comment]
```
       protected URL[] getNLLookupLocations() {
                URL locations[] = {getNLLookupLocation()};
                return locations;
        }

```

It's using C-style array declaration. What does eclipse code style recommend? Using c-style or java-style array declaration?
 Does a cleanup exist for that?

The AST is:
```
           body: 
              Block:(70.41-73,3) 3340ce58 '{'
                statements: 
                - VariableDeclarationStatement:(71.3-71,45) 14499b52 'URL locations[]={getNLLookupLocation()};'
                    type: 
                      SimpleType:(71.3-71,6) 6159fb3c 'URL'
                        name: 
                          SimpleName:(71.3-71,6) 5ac0bf84 'URL'
                            typeBinding: java.net.URL ( )
                    fragments: 
                    - VariableDeclarationFragment:(71.7-71,44) 55fe9c2f 'locations[]={getNLLookupLocation()}'
                        name: 
                          SimpleName:(71.7-71,16) 3580134d 'locations'
                            typeBinding: java.net.URL[] ( ARRAY et=org.eclipse.jdt.core.dom.TypeBinding:java.net.URL)
                        extraDimensions2: 
                        - Dimension:(71.16-71,18) 0be083e1 '[]'
                        initializer: 
                          ArrayInitializer:(71.21-71,44) 4544ab46 'java.net.URL[]' '{getNLLookupLocation()}'
                            typeBinding: java.net.URL[]
                            expressions: 
                            - MethodInvocation:(71.22-71,43) 2052f095 'java.net.URL' 'getNLLookupLocation()'
                                typeBinding: java.net.URL
                                name: 
                                  SimpleName:(71.22-71,41) 76d1f6ea 'org.eclipse.pde.internal.core.plugin.AbstractExtensionsModel.getNLLookupLocation' 'getNLLookupLocation'
                                    typeBinding: java.net.URL ( )
                - ReturnStatement:(72.3-72,20) 3164d5aa 'return locations;'
                    expression: 
                      SimpleName:(72.10-72,19) 68f79b7c 'locations'
                        typeBinding: java.net.URL[] ( ARRAY et=org.eclipse.jdt.core.dom.TypeBinding:java.net.URL)

```

That obviously leads to a class cast exception in org.autorefactor.jdt.internal.ui.fix.RemoveUnnecessaryLocalBeforeReturnCleanUp$ReturnStatementVisitor.removeVariable(RemoveUnnecessaryLocalBeforeReturnCleanUp.java:142).

I may find some time in the evening.
